Added package templates
rancherlabs/corral pull request #50
Opened 2022-04-04 23:25 UTC by jakefhyde

https://github.com/rancherlabs/corral/issues/22

2022-04-05 17:01 UTC, paynejacob requested changes
Overall the functionality from  a user perspective looks good.  I think a lot of this logic should be moved into the package package.  Commands should not contain too much business logic as it makes testing difficult.

2022-04-06 02:19 UTC, paynejacob requested changes
Looking good mostly nits.

2022-04-06 02:19 UTC, paynejacob commented on pkg/package/package.go
> +func (b Package) TerraformRootPath() string {
this is not needed, you can just pass an empty name.

2022-04-06 02:19 UTC, paynejacob commented on pkg/package/template.go
> +		orig := strings.TrimPrefix(path[len(dir):], "/")
there is no need to trim the prefix here POSIX allows for multiple slashes in a path.

2022-04-06 02:19 UTC, paynejacob commented on pkg/package/template.go
> +	return copyFiles(path.Join(root, "overlay"), pkg.OverlayPath(), "/", pkg)
This will break on windows machines, use filepath.Separator or just use filepath.join.

2022-04-06 02:19 UTC, paynejacob commented on pkg/package/template.go
> +			logrus.Debugf("Creating %s", destPath)
```suggestion
			logrus.Debugf("creating %s", destPath)
```

2022-04-06 02:19 UTC, paynejacob commented on pkg/package/template.go
> +			logrus.Debugf("%s -> %s", pkg.Name+orig, destPath)
```suggestion
			logrus.Debugf("%s: %s -> %s", pkg.Name, orig, destPath)
```

2022-04-06 02:19 UTC, paynejacob commented on pkg/package/template.go
> +				logrus.Fatalf("File already exists: %s", destPath)
```suggestion
				logrus.Fatalf("file already exists: %s", destPath)
```

2022-04-06 02:19 UTC, paynejacob commented on pkg/package/template.go
> +		buf, err := ioutil.ReadFile(path.Join(pkg.RootPath, "manifest.yaml"))
https://github.com/rancherlabs/corral/blob/main/pkg/package/package.go#L34

2022-04-06 02:19 UTC, paynejacob commented on pkg/package/template.go
> +func copyFiles(root, dir, sep string, pkg Package) error {
I would not accept the separator here, it over complicates this function.

2022-04-06 02:19 UTC, paynejacob commented on pkg/package/template.go
> +func Template(name, file string) error {
This function belongs in the cmd package.  functions like mergePackages can stay in this package.

2022-04-06 16:42 UTC, paynejacob requested changes
1 minor docs issue, after that looks good.

2022-04-06 16:42 UTC, paynejacob commented on cmd/package/template.go
> +corral template a b c OUT
```suggestion
corral package template a b c OUT 
```

2022-04-06 16:42 UTC, paynejacob commented on cmd/package/template.go
> +corral template -f config.yaml
```suggestion
corral pacakge template -f config.yaml
```

2022-04-06 16:49 UTC, jakefhyde commented on cmd/package/template.go
> +corral template a b c OUT
good catch

2022-04-06 22:42 UTC, jakefhyde commented on cmd/package/template.go
> +corral template a b c OUT
wait I need to make `a b c` work first

2022-04-11 16:52 UTC, merged