move package tutorial out of readme.
rancherlabs/corral pull request #64
Opened 2022-04-28 21:44 UTC by paynejacob

closes #46

2022-04-28 22:10 UTC, jakefhyde approved these changes
just a minor nit, otherwise LGTM!

2022-04-28 22:10 UTC, jakefhyde commented on examples/registry/terraform/main/corral.tf
> +variable "corral_private_key" {} // The corrals public key.  This should be installed on every node.
```suggestion
variable "corral_private_key" {} // The corrals private key.  This should be installed on every node.
```

2022-04-30 00:11 UTC, rmweir requested changes
1 typo but otherwise tutorial looks good to me.

2022-04-30 00:11 UTC, rmweir commented on docs/packages/tutorial.md
> +defines what information is displayed to an end users and what the user is required to provide to use the package.  The
```suggestion
defines what information is displayed to end users and what the user is required to provide to use the package.  The 
```
or
```suggestion
defines what information is displayed to an end user and what the user is required to provide to use the package.  The 
```

2022-04-30 00:18 UTC, merged